# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118xJMn28U657iEI1DZKCMcbIXCS2bd71
"""

memoria = [64, 128, 256, 512]

indice = 0

while indice < len(memoria):
  print(memoria[indice])
  indice +=1

memoria.append(1000)

print(memoria)



memoriaA = []

memoriaA.append(1000)
memoriaA.append(2000)
memoriaA.append(4000)

print(memoriaA)

listaA = ["Dragon", 64, "Dragon de komodo", 128]

listaB = ["tiburon", 256, "ballena"]

for i in lista:
  print(i)

listaA = ["Dragon", 64, "Dragon de komodo", 128]

listaB = ["tiburon", 256, "ballena"]

print(listaB[0])
print(listaA[1])
print(listaA[2])

ListaC = ["juan", "pedro", "laura", "carmen", "susana"]
print(ListaC[-1])
print(ListaC[-2])
print(ListaC[2])
print(ListaC[3])
print(ListaC[4])

memoria = [32, 64, 128, 256, 512]

for q in memoria:
  print(q)

for q in range(len(memoria)):
 print(q)

memoria = [64, 128, 256, 512]

memoria = memoria + [1000, 2000, 4000]

print(memoria)